---
title: "Project Proposal"
author: "Eric Friesth, Aashwin Lamsal, Ethan Wanlass"
date: "10/29/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Team Members: 
Eric Friesth (Project Coordinator), Aashwin Lamsal, Ethan Wanlass

### Data Source: 
https://www.kaggle.com/jameslko/gun-violence-data 

### Dataset Overview: 
This dataset is a collection of incidences where an act of gun violence ocurred in
the U.S. from 2013-2018. 

### Background: 
There are 260,000 records in this dataset with 29 attributes. These attributes are
different descriptors of the gun violence incident, such as the age of the
participant (the shooter) and the number of people killed. There is a lot of
categorical data that will need to be cleaned by being reformatted i.e. split them
into separate columns.

### Plan for Exploratory Analysis:
As for exloratory analysis, we are interested to see if these participants
(shooters) fit specific demographics by looking into the distributions of the
participant's attribute. We would also like to know how these attributes 
correlate or effect one another. It would be nice to discover some sort of 
insight into how we can predict future incidences given certain attributes.

We plan on finding these answers by visualizing the data using distributions of
each attribute with histograms and bar charts as well as compare attributes
against one another using line, bar, and scatter plots. 




